services:

  s-mongo:
    container_name: c-mongo
    image: mongo:8.2.2
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: hoteldocke
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.runCommand('ping').ok == 1" ]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongo-net

  s-mongo-express:
    container_name: c-mongo-express
    image: mongo-express:1.0.2
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@s-mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: false
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - s-mongo
    networks:
      - mongo-net

  s-kafka:
    image: apache/kafka:4.1.0
    container_name: c-kafka
    restart: unless-stopped
    ports:
      - '9092:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://s-kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-net

  s-search-service:
    build:
      context: .
    container_name: c-search-service
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://hotel_user:hotel_pass@s-mongo:27017/hotel?authSource=hotel
      SPRING_DATA_TEST_MONGODB_URI: mongodb://hotel_test_user:hotel_test_pass@s-mongo:27017/hotel_test?authSource=hotel_test
      KAFKA_BOOTSTRAP_SERVERS: s-kafka:9093
    depends_on:
      s-mongo:
        condition: service_healthy
      s-kafka:
        condition: service_started
    networks:
      - kafka-net
      - mongo-net
    profiles:
      - prod

networks:
  kafka-net:
    driver: bridge
  mongo-net:
    driver: bridge
